#### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
#numpy flip располагает элементы в обратном порядке вдоль указанной оси, при этом размеры массива не изменяются.
N = 10
np.flip(np.arange(0, N))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = int(input('Введите количество элементов N: '))
#print(N)
d_matrix = np.diag(np.arange(N), k = 0)
matrix_sum = sum(sum(d_matrix))
print(d_matrix)
print(f'Сумма значений матрицы по диагонали = {matrix_sum}')

Введите количество элементов N: 3
[[0 0 0]
 [0 1 0]
 [0 0 2]]
Сумма значений матрицы по диагонали = 3


#### Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [4]:
from numpy import linalg

In [5]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)
#np.allclose( np.dot(a, linalg.solve(a, b)), b )

array([ 0.46666667,  3.84444444, -5.55555556])

#### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [7]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [8]:
#создадим функцию для подсчёта косинуса угла между векторами

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [42]:
for n, user in enumerate (users_stats):
    near_user_degree = np.arccos(cosine(next_user_stats, user)) * 360 / 2 / np.pi
    
    #print(n, near_user_degree)
    #near_user = min(near_user_degree)
    print(n, near_user_degree)

0 78.46304096718453
1 32.311533237423866
2 66.42182152179818
3 37.761243907035045
4 66.42182152179818
5 90.0
6 90.0
7 18.434948822922017
8 90.0
9 90.0
